#define MAX_MOTS 30

typedef struct {
    char* nom_joueur[24];
    int temps_mis;
    int vitesse;  //WORD PER MINUTE
} JOUEUR; //LA STRUCTURE QUI REPRESENTE UN JOUEUR

JOUEUR joueur_data[2]; //TABLEAU CONTENANT LES JOUEURS

char mots[MAX_MOTS][50]; // TABLEAU QUI VA STOCKER LES MOTS A SAISIR. CHAQUE PEUT AVOIR AU MAXIMUM 50 CARACTERES
char mot_joueur[100]; //VARIABLE QUI VA CONTENIR LE MOT SAISI PAR L'UTILISATEUR